### PR TITLE
Hyperdrive Engaged

### PR DESCRIPTION
**Pull request by ghost**
Please refer to the commit message(s).

### CODE REVIEW

**Comment by AlexChaplinBraz** [comment]
Wow, OK, this is an amazing surprise. My very first pull request, too, so it gives me an opportunity to learn how to do that. This seems like quite a way to make a code review. Easy to see what changed. And I'm starting to understand the quoting better, too. Now, the problem is that I have made some uncommitted changes on my local version, so I'll probably have to learn how to merge those, too. :D 

I'm in the process of switching my setup in quite a major way (can barely even edit files properly), so it will take me a bit more time, but I will definitely go through all that and learn as much as I can. Thank you very much. 

(Also thanks for pointing out the typos, somehow I didn't notice. I'm normally attentive to that, I swear. :P)

**Comment by ghost** [comment]
Lol I'm glad you like the PR. I was supremely happy when I got mine too. :D I rarely get any PRs, though. If you ever spot anything on my stuff, you're more than welcome to send one.

I strongly recommend learning about branches, if you haven't already done so; it's infinitely useful. I always have at least 'dev' and the usual 'master' branches. Lately, I've also found the need for 'feature' branches, for when I'm pushing multiple updates and new programs all in different branches. (sounds cooler than it is; it's a pain juggling it all)

If you like, ignore the PR, get happy with your local changes, then push when you are; that way, it should leave me to do the conflict resolution crap, on my end.

**Comment by AlexChaplinBraz** [comment]
No, I'll pull everything in and learn how to deal with merge conflicts if there are any. I've created one branch so far but I forgot to push it to origin so the "First pass." commit has no context. :D It was the refactor branch for genrepass so I deleted it afterwards anyway, but there doesn't seem to be any history of it left. Still trying to figure it out, but I enjoy it so it's fine.

I just read it all and I agree with most of what you changed, honestly. The more I saw the double quotes the less I liked them. :D So I'll go with that style since it started to make sense half-way through. Still new so I'm not too stuck to one style. Also learned that assigning a variable to a variable also doesn't have word splitting. Never knew.

Kinda started liking this style:
Var=$(
           stuff \
           more stuff
)
For longer ones it looks clearer. Didn't know there's no issue with separating the parenthesis like that. Thought I'd at least have to backslash the first parenthesis but it seems to work regardless. I reckon it's the same for all the ones that expect a closing equivalent, huh. I guess it is pretty standard for curly braces, but somehow it didn't connect in my brain for parenthesis.

I'll do the merger tomorrow. It's already quite late so I'll only mess it all up and not learn anything if I do it now. (And I don't know how much I'll be able to help you since you seem to focus mostly on Perl, a language I know nothing about, but I'll take a look regardless.)

**Comment by ghost** [comment]
Awesome! I'm happy you're happy. Yeah, most of my time is spent in Perl, these days. I still have a crap-ton of Shell programs though, some on which are still worked. It's not just that though, as there's man pages, `README.md` files, things like the `database` file UbuChk uses, etc; help with those is just as appreciated as with the code.

Also, kind of off-topic, but check out the [cheat.sheets](https://github.com/chubin/cheat.sheets) repository; it's really good.

**Comment by AlexChaplinBraz** [comment]
What a nightmarish month. The world right now is really annoying to deal with and it made for an extremely annoying month, too. The most annoying of my life, probably. But thankfully now I'm basically stuck at home so I can do whatever I want. Haven't touched my PC at all so now I have over 4GB of updates. I also feel like a lot of what I was working on is foreign to me. Still, feels good to be back.

I did the local to origin push, then I created a branch for the patches and fixed three merge conflicts. The first one got me confused since I didn't know I had to just `git add` it and `--continue` without committing, but apart from that it went well and I lost my fear of merge conflicts. I'm sure it'll be back once I encounter something hard to fix, but for now I'm happy.

**Comment by ghost** [comment]
Welcome back, Alex. Sorry for the ridiculously late reply. I'm in Hiatus Land. Glad whatever happened was sorted. It'll be tricky for me to get back into the groove of things as well, as I've been away for about a month.

I have been working on a website though, which I will _eventually_ reveal, as it is more or less done and looking quite cool, but I'm not rushing myself. Sometimes I just go into a sort of slump; a funk.

Hope you're well. Stay away from COVID-19!

**Comment by AlexChaplinBraz** [comment]
I feel you. Almost feel like I'm in a constant slump, even though I keep working on stuff. I just jump between projects a lot whenever I'm stuck, so I feel like there's no particular progress on any area. With the current situation it's even worse since there's more time and the world is quite gloomy.

Stay safe ~out~ in there.

**Comment by ghost** [comment]
Good use of strikethrough. :D

**Pull request closed without merging**
